config/routes.rb
Rails.application.routes.draw do
  get 'about', to: 'posts#about'
  root 'posts#index'
  resources :posts do
      resources :comments
  end
  get 'signup', to: 'users#new'
  post 'signup', to: 'users#create'
  resources :users, except: [:new]
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user

  validates :name, presence: true
  validates :comment, presence: true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments

  validates :title, presence: true, length: {minimum: 3, maximum: 25}
  validates :body, presence: true, length: {minimum:100}
end

app/models/user.rb
class User < ApplicationRecord
  before_save{ self.email = email.downcase}
  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  validates :username, presence: true, uniqueness: {case_sensitive: false}, length: {minimum: 4, maximum: 25}
  validates :email, presence: true, uniqueness: {case_sensitive: false}, format: {with: /\A([\w+\-]\.?)+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i}

  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  helper_method :current_user, :logged_in?

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.new(authenticated_params)
    @comment.user_id = current_user.id
    @comment.name = current_user.username
    flash[:error] = "Comment Box is Empty!!!" unless @comment.save
    redirect_to post_path(@post, anchor: 'comment')
  end

  def destroy
    comment = Comment.find(params[:id])
    comment.destroy
    redirect_to post_path params[:post_id]
  end

  private

  def authenticated_params
    params.require(:comment).permit(:name,:comment)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  before_action :verify_login, only: [:new, :edit]

  def about
  end

  def index
    @posts = Post.paginate(page: params[:page], per_page: 9).order(created_at: :desc)
  end

  def show
    @post = Post.find(params[:id])
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(authenticated_params)
    @post.user = current_user
    if @post.save
      redirect_to @post
    else
      flash.now[:error] = check_error
      render :new
    end
  end

  def edit
    @post = Post.find(params[:id])
    redirect_to posts_path unless @post.user == current_user || current_user.admin?
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(authenticated_params)
      redirect_to @post
    else
      flash.now[:error] = check_error
      render :edit
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to posts_path
  end

  private

  def authenticated_params
    params.require(:post).permit(:title, :body)
  end

  def verify_login
    redirect_to login_path unless logged_in?
  end

  def check_error
    if params[:post][:title].empty?
      "The post should have a valid title."
    elsif params[:post][:title].length < 3
      "Title is too short. Minimum is 3 characters."
    elsif params[:post][:title].length > 25
      "Title is too big. Maximum is 25 characters."
    elsif params[:post][:body].empty?
      "The post contents are empty!!!"
    elsif params[:post][:body].length < 100
      "Content should have at least 100 characters"
    end
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      redirect_to posts_path
    else
      flash.now[:notice] = check_for_error user
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to login_path
  end

  private

  def check_email
    if params[:session][:email].empty?
      "Mail ID is empty"
    elsif not params[:session][:email] =~  /\A([\w+\-]\.?)+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i
      "Invalid Mail ID"
    end
  end

  def check_password(user)
    unless user.authenticate(params[:session][:password])
      "Incorrect password, pls try again!"
    end
  end

  def check_for_error(user)
    flash.now[:error] = check_email
    return "email" if flash[:error]
    flash.now[:error] = check_password user
    return "wrong-password" if flash[:error]
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(authenticated_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to user_path @user
    else
      flash.now[:notice] = check_error @user
      render :new
    end
  end

  def index
    @users = User.order(username: :asc)
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
    redirect_to user_path(@user) unless current_user == @user
  end

  def update
    @user = User.find(params[:id])
    if @user.update(authenticated_params)
      redirect_to user_path(@user)
    else
      flash.now[:error] = check_username @user
      render :edit
    end
  end

  def destroy
    user = User.find(params[:id])
    session[:user_id] = nil unless current_user.admin?
    user.destroy
    redirect_to signup_path
  end

  private

  def authenticated_params
    params.require(:user).permit(:username,:email,:password)
  end

  def check_password(user)
    if user.errors.include?(:password)
      "Invalid Password!"
    end
  end

  def check_email
    if params[:user][:email].empty?
      "Mail ID is empty"
    elsif not params[:user][:email] =~  /\A([\w+\-]\.?)+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i
      "Invalid Mail ID"
    end
  end

  def check_username(user)
    if params[:user][:username].empty?
      "The username field is empty"
    elsif params[:user][:username].length < 4
      "The username is too small!"
    elsif params[:user][:username].length > 25
      "The username is too big!!"
    elsif user.errors.include?(:username)
      "That username is already taken"
    end
  end

  def check_error(user)
    flash.now[:error] = check_username user
    return "username" if flash[:error]
    flash.now[:error] = check_email
    return "email" if flash[:error]
    flash.now[:error] = check_password user
    return "password" if flash[:error]
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def gravatar_link (user, option = {size: 250})
    hash = Digest::MD5.hexdigest(user.email.downcase)
    size = option[:size]
    "https://www.gravatar.com/avatar/#{hash}?s=#{size}"
  end

  def markdown
    markdown = Redcarpet::Markdown.new(Redcarpet::Render::HTML.new(escape_html: true, hard_wrap: true), autolink: true, tables: true)
  end

end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Narrate it!</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
	
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
	<%= favicon_link_tag 'favicon.ico' %>
    <%= stylesheet_link_tag 'application', 'https://fonts.googleapis.com/css2?family=Rancho&family=Klee+One:wght@400;600&family=Mate+SC&family=Ubuntu:wght@300;400&family=Balsamiq+Sans&family=Nixie+One&family=Special+Elite&display=swap', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
	<%= javascript_pack_tag 'index' %>
  </head>

  <body>
  	<div class="nav">
		<a href=<%= posts_path %>><h1 class = "main-title">Narrate-it!</h1></a>
	</div>
	<a class="sandwich">
		<div class="bread b1"></div>
		<div class="bread b2"></div>
		<div class="bread b3"></div>
	</a>
	<div class="screen"></div>
	<div class="nav-items" >
		<a class="sandwich2"></a>
		<% if logged_in? %>
			<%= link_to "+Create", new_post_path, class: "nav-item" %>
			<%= link_to "About", about_path, class: "nav-item" %>
			<%= link_to "Profile", user_path(current_user), class: 'nav-item' %>
			<% if current_user.admin? %>
				<%= link_to "Dashboard", users_path, class: "nav-item" %>
			<% end %>
			<%= link_to "Logout", logout_path, method: :delete, data: { confirm: "Are you sure?" }, class: "nav-item" %>
		<% else %>
			<%= link_to "About", about_path, class: "nav-item" %>
			<%= link_to 'Sign In', signup_path, class: "nav-item"%>
		<% end %>
	</div>
    <%= yield %>
  	<footer>Copyright © Sriram V (2021)</footer>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with model: post, class: 'form' do |form|  %>
	<%= form.text_field :title, class: "title-input", autocomplete: 'off', spellcheck: 'false', placeholder: 'Title' %>  <%= form.submit value, class: 'colored-btn form-btn' %> <br>
	<div class="error form-error"><%= flash[:error] if flash[:error] %></div>
	<%= form.text_area :body, class: "body-input", autocomplete: 'off' %> <br>
<% end %>

app/views/posts/_posts.html.erb
<div class="posts">
	<% if posts %>
		<% posts.each do |post| %>
			<div class="index-post">
				<p class="date"><%= post.created_at.strftime("%d-%b-%Y") %></p>
				<p class="index-title"><%= truncate(post.title, length: 15) %></p>
				<p class="index-user">by <%= link_to post.user.username, user_path(post.user) %></p>
				<% if post.user == current_user || (logged_in? && current_user.admin?) %>
					<div class='icons'>
						<%= link_to edit_post_path(post) do %>
							<i class="far fa-edit icon"></i>
						<% end %>
						<%= link_to(post_path(post), method: :delete, data: { confirm: 'This will permanently delete the post, are you sure?' }) do %>
							<i class="far fa-trash-alt icon"></i>
						<% end %>
					</div>
				<% end %>
				<p class="index-body"><%= truncate(post.body, length: 300) %></p>
				<%= button_to "Read More", post_path(post), method: :get, class: 'read-btn' %>
			</div>
		<% end %>
	<% else %>
		<div class="handler">No posts have been created yet</div>
	<% end %>
	
</div>

<%= will_paginate posts, container: false, renderer: WillPaginate::ActionView::BootstrapLinkRenderer %>

app/views/posts/about.html.erb
<div class="about">
	<h2 class= "about-title">About</h2>
	<p>Narrate-it is a blogging website I created as part of my college project. In Narrate-it, everyone can post a blog about their daily life and routine stuffs. You must have an account to create a blog. You are humbly requested to follow the guidelines and regulation and not to post anything offensive. <br/> <br/> The posts created in narrate-it uses <a href="https://www.markdownguide.org/cheat-sheet/">markdown formatting</a> style. Any styles applied in markdown (*.md file) can also applied while creating a post in the blog. Your profile picture will be your image associated with your <a href="https://en.gravatar.com/">gravatar</a> by default as of now. The custom profile picture feature may be updated in future. You can't change your password once you created the account. Don't forget to take note of it.</p>
	<p class="congrats">Happy blogging!!!</p>
</div>

app/views/posts/edit.html.erb
<%= render 'form', post: @post, value: 'Save' %>

app/views/posts/index.html.erb
<h2 class="index-about"> Recent Posts </h2>
<%= render 'posts/posts', posts: @posts %>

app/views/posts/new.html.erb
<%= render 'form', post: @post, value: 'Create' %>

app/views/posts/show.html.erb
<div class="the-post">
	<h1 class="post-title"><%= @post.title %></h1>
	<div class="index-body post-body"><%== markdown.render(@post.body) %></div>
	<div class="bg-img1"></div>
	<div class="bg-img2"></div>
	<div class="bg-img3"></div>
	<div class="bg-img4"></div>
</div>

<% if @post.user == current_user || (logged_in? && current_user.admin?) %>
		<div class='edit-post'><i class="far fa-edit icon"></i> <%= link_to 'Edit', edit_post_path(@post) %></div>
<% end %>

<div class="author">
	<p class="author-name">by <%= link_to @post.user.username, user_path(@post.user) %></p>
	<p class="author-date">last modified at <%= @post.updated_at.strftime("%d-%b-%Y") %></p>
</div>

<div class="comment-section" id="comment">
	<h3 class="comments"><%= "Comments:" if @post.comments.any? %></h3>
	<% @post.comments.each do |c| %>
		<div class='single-cmnt'>
			<p class="commenter"><%= link_to c.name, user_path(c.user) %></p>
			<p class="comment"><%= c.comment %></p>
			<% if c.user == current_user || (logged_in? && current_user.admin?) %>
				<%= link_to post_comment_path(@post, c), method: :delete, class: 'delete-cmnt' do %>
					<i class="far fa-trash-alt icon"></i>
				<% end %>
			<% end %>
		</div>
	<% end %>
	
	<% if logged_in? %>
		<h4 class="comments">Add Comment:</h4>
		<%= form_with model: [@post, @post.comments.build], class: 'cmnt-form' do |f| %>
			<%= f.text_area :comment, class: "body-input cmnt-body" %> <br/>
			<%= f.submit "Add", class: "colored-btn cmnt-btn" %> <br/>
		<% end %>
	<% end %>
	<div class="error"><%= flash[:error] if flash[:error] %></div>
	
</div>

app/views/signin/_form.html.erb
<div class="sign-in">
	<table>
		<tr>
			<th class=<%= "switch" if type == 'login' %>><%= link_to 'Sign Up', signup_path %></th>
			<th class=<%= "switch" if type == 'signup' %>><%= link_to 'Log In', login_path %></th>
		</tr>
		<tr>
			<td colspan='2'>
				<%= form_with scope: type=="signup" ? :user : :session, url: type=="signup" ? signup_path : login_path, class: 'sign-in-form' do |f| %>
					<% if type == 'signup' %>
						<p class="label">Username:</p>
						<%= f.text_field :username, spellcheck: 'false', class: 'sign-in-input' %><br/>
						<% if flash[:notice] == "username" %>
							<div class="error form-error"><%= flash[:error] %></div>
						<% end %>
					<% end %>
					
					<p class="label">Email:</p>
					<%= f.text_field :email, class: 'sign-in-input' %><br/>
					<% if flash[:notice] == "email" %>
						<div class="error form-error"><%= flash[:error] %></div>
					<% end %>
					
					<p class="label">Password:</p>
					<% if type == 'signup' %>
						<%= f.text_field :password, spellcheck: 'false', autocomplete: 'off', class: 'sign-in-input' %><br/>
						<% if flash[:notice] == "password" %>
							<div class="error form-error"><%= flash[:error] %></div>
						<% end %>
					<% elsif type == 'login' %>
						<%= f.password_field :password, spellcheck: 'false', autocomplete: 'off', class: 'sign-in-input' %><br/>
						<% if flash[:notice] == "wrong-password" %>
							<div class="error form-error"><%= flash[:error] %></div>
						<% end %>
					<% end %>
					<div class="center-btn">
						<%= f.submit type=='login' ? 'Log In' : 'Sign Up', class: 'colored-btn sign-up-btn' %>
					</div>
				<% end %>
			</td>
		</tr>
	</table>
</div>

app/views/users/_profile.html.erb
<div class="profile-icons">
	<% if type == "edit" %>
		<%= form.submit "Save", class: 'colored-btn' %>
	<% else %>
		<% if current_user == @user %>
			<%= link_to edit_user_path(@user) do %>
				<i class="fas fa-user-edit icon"></i>
			<% end %>
		<% end %>
		<% if current_user == @user || (logged_in? && current_user.admin?) %>
			<%= link_to(user_path(@user), method: :delete, data: { confirm: 'This will permanently delete this account along with the posts associated with it, are you sure?' }) do %>
				<i class="far fa-trash-alt icon"></i>
			<% end %>
		<% end %>
	<% end %>
</div>

<div class="profile">
	<div class="container">
		<div class="row">
			<div class="col-4 col-sm-5 col-lg-6 image-box">
				<div class="circles">
					<%= image_tag gravatar_link(@user), alt: @user.username, class: 'profile-image' %>
					<div class='gradient-circle'></div>
					<div class='pop-up'> Your gravatar profile appears here! </div>
					<% if @user.admin? %>
						<%= image_tag 'admin.png', class: 'crown' %>
					<% end %>
				</div>
			</div>
			<div class="col-8 col-sm-7 col-lg-6 details-box">
				<% if type == "edit" %>
					<h1 class="profile-name"><%= form.text_field :username, autocomplete: 'off', spellcheck: 'false', class: 'profile-edit' %></h1>
					<div class="error form-error"><%= flash[:error] %></div>
				<% else %>
					<h1 class="profile-name"><%= @user.username %></h1>
				<% end %>
				<h2 class="profile-email"><%= @user.email %></h2>
			</div>
		</div>
	</div>
</div>

<% if @user.posts.any? %>
	<h2 class="recent">Latest Posts</h2>
	<%= render 'posts/posts', posts: @user.posts.paginate(page: params[:page], per_page: 3).order(created_at: :desc) %>
<% end %>

app/views/users/edit.html.erb
<%= form_with model:@user do |form|%>
	<%= render "profile", type:"edit", form: form %>
<% end %>

app/views/users/index.html.erb
<h2 class="users-heading">Our Precious Bloggers</h2>

<div class="users-card-box">
	<% @users.each do |user| %>
		<div class="user-card">
			<%= link_to user_path(user) do %>
				<%= image_tag(gravatar_link(user), alt: user.username, class: "user-image") %>
				<p class="user-name"><%= user.username %> <%= "(admin)" if user.admin? %></p>
				<p class="joined-date">Joined <%= time_ago_in_words(user.created_at) %> ago</p>
			<% end %>
		</div>
	<% end %>
</div>

app/views/users/new.html.erb
<%= render 'signin/form', type: 'signup'%>

app/views/users/show.html.erb
<%= render "profile", type: "show" %>